Repository wecode-bootcamp-korea/13-BeautyOfFunction-backend, pull requests merged in 2020-11, with the labels that each got.

#1 [허소정][feature/user] Modify: user 모델 수정
  functionofbeauty/settings.py
  user/__init__.py
  user/admin.py
  user/apps.py
  user/migrations/0001_initial.py
  user/migrations/0002_auto_20201104_1204.py
  user/migrations/__init__.py
  user/models.py
  user/tests.py
  user/views.py
Labels: Status: 리뷰 요청

#2 [허소정][feature/quiz] Add: quiz앱 생성 & 모델 작성
  functionofbeauty/settings.py
  quiz/__init__.py
  quiz/admin.py
  quiz/apps.py
  quiz/migrations/0001_initial.py
  quiz/migrations/__init__.py
  quiz/models.py
  quiz/tests.py
  quiz/views.py
Labels: Status: 리뷰 요청

#3 [허소정][feature/review] Modify: review 모델 수정
  functionofbeauty/settings.py
  review/__init__.py
  review/admin.py
  review/apps.py
  review/migrations/0001_initial.py
  review/migrations/0002_review_user.py
  review/migrations/__init__.py
  review/models.py
  review/tests.py
  review/views.py
Labels: Status: 리뷰 요청

#4 [김예진][feature/product] Add : product 앱 생성 & 모델 작성
  functionofbeauty/settings.py
  product/__init__.py
  product/admin.py
  product/apps.py
  product/migrations/0001_initial.py
  product/migrations/__init__.py
  product/models.py
  product/tests.py
  product/urls.py
  product/views.py
Labels: Status: 리뷰 요청

#5 [김예진][feature/cart]Add : cart 앱 추가, 모델 작성
  cart/__init__.py
  cart/admin.py
  cart/apps.py
  cart/migrations/0001_initial.py
  cart/migrations/__init__.py
  cart/models.py
  cart/tests.py
  cart/views.py
  functionofbeauty/settings.py
Labels: Status: Accepted

#7 [김예진][feature/cart]모델(created_at -> updated_at으로) 수정
  cart/models.py
Labels: Status: 리뷰 요청

#8 [허소정][feature/user#2] Modify: order foreign key 추가
  cart/migrations/0002_auto_20201105_1330.py
  product/migrations/0002_auto_20201105_1330.py
  user/migrations/0003_subscription_order.py
  user/models.py
Labels: Status: Accepted

#9 [허소정][feature/review#2] Modify: order foreign key 추가
  cart/migrations/0002_auto_20201105_1337.py
  product/migrations/0002_auto_20201105_1337.py
  review/migrations/0003_review_order_item.py
  review/models.py
Labels: Status: Accepted

#10 [김예진][feature/product#2]migration 삭제 후 재생성
  .gitignore
  cart/migrations/0001_initial.py
  cart/migrations/0002_auto_20201105_1330.py
  cart/migrations/0002_auto_20201105_1337.py
  cart/migrations/0002_order_user.py
  cart/models.py
  product/migrations/0001_initial.py
  product/migrations/0002_auto_20201105_1330.py
  product/migrations/0002_auto_20201105_1337.py
  product/models.py
  quiz/migrations/0001_initial.py
  review/migrations/0001_initial.py
  review/migrations/0002_review_user.py
  review/migrations/0003_review_order_item.py
  user/migrations/0001_initial.py
  user/migrations/0002_auto_20201104_1204.py
  user/migrations/0003_subscription_order.py
Labels: Status: 리뷰 요청

#11 [김예진][feature/product#2]model 수정,migration 삭제 후 재생성
  cart/migrations/0001_initial.py
  cart/migrations/0002_order_user.py
  cart/models.py
  product/migrations/0001_initial.py
  product/models.py
  quiz/migrations/0001_initial.py
  review/migrations/0001_initial.py
  user/migrations/0001_initial.py
Labels: Status: 리뷰 요청

#12 [허소정][feature/user#2] Modify: User 모델 수정
  user/migrations/0002_auto_20201107_0650.py
  user/models.py
Labels: Status: 리뷰 요청

#14 [허소정][feature/quiz] Modify: Quiz 모델 수정
  quiz/migrations/0002_auto_20201107_1230.py
  quiz/models.py
Labels: Status: Accepted

#15 [김예진][feature/product#2]product models.py 수정
  product/migrations/0002_auto_20201106_1322.py
  product/models.py
Labels: Status: 리뷰 요청

#16 [허소정][feature/django_setting] 장고 CORS 세팅
  functionofbeauty/settings.py
Labels: Status: 리뷰 요청

#17 [허소정][feature/user#2] Modify: User 모델 수정
  user/models.py
Labels: Status: 리뷰 요청

#13 [허소정][feature/user] Add: 회원가입, 로그인, 소셜로그인 엔드포인트 생성
  functionofbeauty/urls.py
  user/migrations/0003_auto_20201109_0451.py
  user/tests.py
  user/urls.py
  user/utils.py
  user/views.py
Labels: Status: 리뷰 요청

#19 [허소정][feature/quiz#2] Modify: Quiz 모델 수정
  quiz/models.py
Labels: Status: 리뷰 요청

#22 [허소정][feature/user] Add: Mypage 엔드포인트 추가
  Dockerfile
  requirements.txt
  user/tests.py
  user/urls.py
  user/utils.py
  user/views.py
  user_uploader.py
Labels: Status: 리뷰 요청

#20 [김예진][feature/product#3]product endpoint 구현
  functionofbeauty/urls.py
  product/migrations/0002_auto_20201109_0543.py
  product/migrations/0003_merge_20201111_0641.py
  product/models.py
  product/tests.py
  product/urls.py
  product/views.py
Labels: Status: 리뷰 요청

#21 [허소정][feature/quiz] Add: Quiz 엔드포인트 생성
  functionofbeauty/urls.py
  quiz/tests.py
  quiz/urls.py
  quiz/views.py
  utils.py
Labels: Status: 리뷰 요청

#23 [김예진]Feature/product#3
  cart/migrations/0003_orderitem_review.py
  cart/models.py
  product/views.py
  quiz/migrations/0004_auto_20201112_1513.py
  review/migrations/0002_remove_review_order_item.py
  review/models.py
Labels: Status: 리뷰 요청

#25 [김예진][Feature/product#3] View 수정
  product/views.py
Labels: Status: 리뷰 요청

#24 add : review endpoint 완성
  Dockerfile
  cart/migrations/0003_orderitem_review.py
  functionofbeauty/urls.py
  quiz/migrations/0004_auto_20201111_1533.py
  review/migrations/0002_remove_review_order_item.py
  review/urls.py
  review/utils.py
  review/views.py
Labels: Status: Conflict 해결 요청

#26 [허소정][feature/user]Fix: 오타 수정
  user/utils.py
  user/views.py
Labels: Status: 리뷰 요청
